### ISSUE TITLE
Actions can't access updated code, limited to code released 3 years ago

### ISSUE THREAD

**Issue by undeadbanana** [cwtools/cwtools-action#9]
Apologies, I'm kind of new to the whole actions thing but I couldn't find any way to reference the updated code. 

Setting up the action using the given installation instructions just produced errors because I'm using the tools for validating ck3 mods and that wasn't added until after the initial release. Forking and releasing a version in my own repositories allowed me to set up the action and it worked flawlessly.

**Comment by soryy708** [comment]
The maintainer must make a release, for us to use something that isn't v1.0.0 (as in `cwtools/cwtools-action@v1.0.0`)

**Comment by Yard1** [comment]
Oh wow, I completely forgot to make one back then 😓 Let me update this when I have a moment.
